[package]
name = "srm"
version = "0.1.0"
edition = "2021"
authors = ["cuervo-blanco"]
description = "A safe remove (srm) tool in Rust with collector functionality"
license = "MIT"
repository = "https://github.com/cuervo-blanco/utilities"

[dependencies]

